/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Hytale Server JAR
    compileOnly(files("libs/HytaleServer.jar"))
    testImplementation(files("libs/HytaleServer.jar"))
    
    // JSR 305 annotations (provides @Nonnull)
    implementation("com.google.code.findbugs:jsr305:3.0.2")
    testImplementation("com.google.code.findbugs:jsr305:3.0.2")
    
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "hytale.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Lire le manifest.json pour extraire le nom et la version
fun readManifestProperty(property: String): String {
    val manifestFile = file("src/main/resources/manifest.json")
    if (!manifestFile.exists()) return ""
    
    val content = manifestFile.readText()
    val regex = "\"$property\"\\s*:\\s*\"([^\"]+)\"".toRegex()
    val match = regex.find(content)
    return match?.groupValues?.get(1) ?: ""
}

// Configurer le nom du JAR en fonction du manifest.json
val pluginName = readManifestProperty("Name")
val pluginVersion = readManifestProperty("Version")

if (pluginName.isNotEmpty()) {
    tasks.named<Jar>("jar") {
        archiveFileName.set("$pluginName.jar")
    }
}
